/* Adding User */
DROP USER meters_admin;

CREATE USER meters_admin IDENTIFIED BY Welcome1#Welcome1#;
GRANT RESOURCE, UNLIMITED TABLESPACE, CREATE ANY TABLE, CREATE SESSION, SELECT ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE, UPDATE ANY TABLE TO meters_admin;


/* Adding Sequence for Auto-increment */

/* METERS */

DROP SEQUENCE meters_admin.METERS_seq;

ALTER TABLE meters_admin.METERS ADD (
  CONSTRAINT METERS_pk PRIMARY KEY (ID));

CREATE SEQUENCE meters_admin.METERS_seq START WITH 100;

CREATE OR REPLACE TRIGGER METERS_bir 
BEFORE INSERT ON meters_admin.METERS 
FOR EACH ROW

BEGIN
  SELECT meters_admin.METERS_seq.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

insert into meters_admin.METERS (DEVICE_ID,	DEVICE_EVENT,	DEVICE_TEMP,	DEVICE_BATTERY_PCT,	DEVICE_USAGE,	DEVICE_LAT,	DEVICE_LONG,	DEVICE_DATE_TIME,	DEVICE_NAME,	DEVICE_MODEL,	DEVICE_MANAGER) values (11111, 'UP', 89, 90, 70, -37.835311, 144.9725336, '2018-07-29 09:17:13.812189', 'Device103', 'MH 109', 'Origin');
insert into meters_admin.METERS (DEVICE_ID,	DEVICE_EVENT,	DEVICE_TEMP,	DEVICE_BATTERY_PCT,	DEVICE_USAGE,	DEVICE_LAT,	DEVICE_LONG,	DEVICE_DATE_TIME,	DEVICE_NAME,	DEVICE_MODEL,	DEVICE_MANAGER) values (11111, 'DOWN', 89, 90, 70, -37.835311, 144.9725336, '2018-07-29 09:17:13.812189', 'Device103', 'MH 109', 'Origin');
commit;
